# crate-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crate-backend
  template:
    metadata:
      labels:
        app: crate-backend
    spec:
      containers:
      - name: crate-backend
        image: code_crate-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        resources:
          requests:
            memory: "400Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"