apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'true'
        - name: MYSQL_DATABASE
          value: crate
        resources:
          requests:
            memory: "300Mi"  # Request 64 megabytes of memory
            cpu: "250m"      # Request 250 milliCPU (0.25 CPU cores)
          limits:
            memory: "500Mi" # Limit memory usage to 500 megabytes
            cpu: "500m"     # Limit CPU usage to 500 milliCPU (0.5 CPU cores)

