apiVersion: v1
kind: Service
metadata:
  name: crate-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: crate-frontend
