# crate-frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crate-frontend
  template:
    metadata:
      labels:
        app: crate-frontend
    spec:
      containers:
      - name: crate-frontend
        image: code_crate-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_HOST
          value: "crate-backend"
        - name: BACKEND_PORT
          value: "8000"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
